<?php 
	$cust = $this->customer;
	$state = $cust->address->state;
?>
<div class="add-address-wrapper">
<div class="add-address info-box">
  <h4><span>New Address</span></h4>
		<form id="add-address-form">
        <div class="new_account_wrapper">
  	    <div class="box_wrapper_info_l">
      
      <label>Company:</label>
      <input type="text" maxlength="30" size="30" id="company" name="company" value="<?php echo $cust->address->company ?>" >
      <label>Address Line 1:</label>
      <input type="text" maxlength="30" size="30" id="address1" name="address1" value="<?php echo $cust->address->address1 ?>">
      <label>Address Line 2:</label>
      <input type="text" maxlength="30" size="30" id="address2" name="address2" value="<?php echo $cust->address->address2 ?>">
      <label>City:</label>
      <input type="text" maxlength="30" size="30" id="city" name="city" value="<?php echo $cust->address->city ?>" >
      <label>State / Province</label>
      <select name="state" id="state">
      <option value="AL">Alabama</option>
      <option value="AK">Alaska</option>
      <option value="AZ">Arizona</option>
      <option value="AR">Arkansas</option>
      <option value="CA">California</option>
      <option value="CO">Colorado</option>
      <option value="CT">Connecticut</option>
      <option value="DE">Delaware</option>
      <option value="DC">District Of Columbia</option>
      <option value="FL">Florida</option>
      <option value="GA">Georgia</option>
      <option value="HI">Hawaii</option>
      <option value="ID">Idaho</option>
      <option value="IL">Illinois</option>
      <option value="IN">Indiana</option>
      <option value="IA">Iowa</option>
      <option value="KS">Kansas</option>
      <option value="KY">Kentucky</option>
      <option value="LA">Louisiana</option>
      <option value="ME">Maine</option>
      <option value="MD">Maryland</option>
      <option value="MA">Massachusetts</option>
      <option value="MI">Michigan</option>
      <option value="MN">Minnesota</option>
      <option value="MS">Mississippi</option>
      <option value="MO">Missouri</option>
      <option value="MT">Montana</option>
      <option value="NE">Nebraska</option>
      <option value="NV">Nevada</option>
      <option value="NH">New Hampshire</option>
      <option value="NJ">New Jersey</option>
      <option value="NM">New Mexico</option>
      <option value="NY">New York</option>
      <option value="NC">North Carolina</option>
      <option value="ND">North Dakota</option>
      <option value="OH">Ohio</option>
      <option value="OK">Oklahoma</option>
      <option value="OR">Oregon</option>
      <option value="PA">Pennsylvania</option>
      <option value="PR">Puerto Rico</option>
      <option value="RI">Rhode Island</option>
      <option value="SC">South Carolina</option>
      <option value="SD">South Dakota</option>
      <option value="TN">Tennessee</option>
      <option value="TX">Texas</option>
      <option value="UT">Utah</option>
      <option value="VT">Vermont</option>
      <option value="VA">Virginia</option>
      <option value="WA">Washington</option>
      <option value="WV">West Virginia</option>
      <option value="WI">Wisconsin</option>
      <option value="WY">Wyoming</option>
      <option value="AB">Alberta</option>
      <option value="BC">British Columbia</option>
      <option value="MB">Manitoba</option>
      <option value="NB">New Brunswick</option>
      <option value="NL">Newfoundland and Labrador</option>
      <option value="NS">Nova Scotia</option>
      <option value="ON">Ontario</option>
      <option value="PE">Prince Edward Island</option>
      <option value="QC">Quebec</option>
      <option value="SK">Saskatchewan</option>
      <option value="NT">Northwest Territories</option>
      <option value="NU">Nunavut</option>
      <option value="YT">Yukon</option>
    </select>
    <label>Zip / Postal Code:</label>
    <input type="text" maxlength="30" size="30" id="zip" name="zip" value="<?php echo $cust->address->zip ?>">
   </div>
 	 	 <div class="box_wrapper_info_r">
    <label>Country:</label>
    <select name="country" id="country">
      <option value="USA">United States</option>
      <option value="Canada">Canada</option>
    </select>
    <label>Phone Number:</label>
    <input type="text" maxlength="30" size="30" id="phone" name="phone" value="<?php echo $cust->address->phone ?>">
    <label>E-Mail:</label>
    <input type="text" maxlength="30" size="30" id="email" name="email" value="<?php echo $cust->address->email ?>">
    <div class="save-button">
      <div id="proceed_new" class="update_button proceed"><span>Save</span>
      </div>
    </div>
  </div>
  	  	<div class="close-button-wrapper">
      		<a>close</a>
        </div>
  </div>	
  		</form>
  </div>
  </div>