<?php 
	$cust = $this->customer;
	$state = $cust->address->state;
?>
<div class="change-password-wrapper">
<div class="change-password info-box">
  <h4><span>Change Password</span></h4>
		<form id="change-password-form">
        <div class="new_account_wrapper">
          <label>Old Password:</label>
          <input type="password" maxlength="30" size="30" id="old-pass" name="old-pass" value="" >
          <label>New Password:</label>
          <input type="password" maxlength="30" size="30" id="new-pass" name="new-pass" value="">
          <label>Reenter New Password:</label>
          <input type="password" maxlength="30" size="30" id="new-pass2" name="new-pass2" value="">
          <div class="save-button">
            <div id="proceed_new" class="update_button proceed"><span>Save</span></div>
          </div>
  	  	
        
        
        
        
        
        <div class="close-button-wrapper">
      		<a>close</a>
        </div>
  </div>	
  		</form>
  </div>
  </div>
  
  
  
  
  
