<?php $this->headScript()->appendFile("/scripts/pass_recover.js"); ?>

<div class="main_wrapper_info">
  <h4 class="shipping-header">Password recovery</h4>
  <div class="return_cust info-box">
    <h4><span>Password Recovery</span></h4>
      <div class="password-reset-note">
      	<span>Please enter your login information.  New password will be send to the email listed on the account.</span>
      </div>
      <label>Login: </label>
      <input type="text" maxlength="30" size="30" id="login_email" name="login_email">
      <div class="checkout_button">
        <div id="proceed_login" class="update_button proceed"><span>Reset Password</span></div>
      </div>
  </div>
</div>