

<div style="background-color: #26BEF0; padding: 30px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
  <p style= "color: #FFF;font-size: 12px;">Someone, hopefully you requested password change for account with our cart. </p>
  <p style= "color: #FFF;font-size: 12px;">Customer:</p>
  <table width="454" border="1" cellspacing="0">
    <tr>
      <td style="color: #FFF;background-color: #0A6989;font-weight: bold;padding: 5px;" width="126">Login</td>
    </tr>
    <tr>
      <td style="color: #FFF;padding:5px;background: white;color: #0A6989;font-size: 12px;"><?php echo $this->customer->username ?></td>
    </tr>
  </table>
  <p style="font-size: 12px; display: block; width: 600px; color: white; ">Please click on the following link to reset your password. New generated password will be sent to you shortly. If you believe this is a mistake do not click on the following link.</p>
  <p style="font-size: 12px; display: block; color: white; ">Click to reset Password:</p> 
  <a href="<?php echo $this->website->cart_base."/account/cpc/u/".$this->customer->id."/s/".$this->secret; ?>"><?php echo $this->website->cart_base."/account/cpc/u/".$this->customer->id."/s/".$this->secret; ?></a>
  <br/><br/>
  <div style="	background: white;padding: 30px; width: 540px;">
    <h4 style="	color: #BF0000;	font-size: 18px;background-color: #FFF;padding: 5px;">Please Note:</h4>
    <p> <strong>Do not reply to this email.</strong></p>
    <p> PLEASE CALL Toll Free: 1-800-856-8397  if you have any additional questions. </p>
  </div>
  <p style="color: #FFF;font-size: 12px;">Thank You,</p>
  <p style="color: #FFF;font-size: 12px;"><?php echo $this->website->site_name ?><br />
  </p>
</div>
