<div class="main_wrapper_info">
  <h4 class="shipping-header">Thank you for your order!</h4>
  <div class="thank_box info-box">
    <p><span class="thank_text">Thank You!</span><br><br />
    <strong>Your Order ID is: <?php echo $this->order_number; ?> </strong><br /><br />
      Keep this confirmation for your records</p>
    You have successfully placed your order. You will recieve a confirmation e-mail shortly to [e-mail address].<br>
    <br>
    Most orders will arrive within 7-10 days of purchase. You can log in to <a href="#">your account </a> to track the status of your order. Please allow 24 hours for your account to update to reflect your new purchse. <br>
    <br>
    If you paid with PayPal Bill Me Later please <a href="#">go here</a> to finalize your payment. Please be aware that your order will not be processed or shipped until full payment is recieved. <br>
    <br>
    For money orders, please reference your order number on payment. Orders will not be processed or shipped until full payment is received. Please mail payment in to:<br>
    MiniMax Electronics<br>
    2201 S Union<br>
    Chicago, IL 60616. </div>
    <div class="checkout_button">
    <div class="update_button tosite"><span>Continue to 123DJ</span></div>
    </div>
</div>